// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/transaction/txn.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	txn "github.com/rishu/microservice/pkg/transaction"
)

// MockTransactionManager is a mock of TransactionManager interface.
type MockTransactionManager struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionManagerMockRecorder
}

// MockTransactionManagerMockRecorder is the mock recorder for MockTransactionManager.
type MockTransactionManagerMockRecorder struct {
	mock *MockTransactionManager
}

// NewMockTransactionManager creates a new mock instance.
func NewMockTransactionManager(ctrl *gomock.Controller) *MockTransactionManager {
	mock := &MockTransactionManager{ctrl: ctrl}
	mock.recorder = &MockTransactionManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionManager) EXPECT() *MockTransactionManagerMockRecorder {
	return m.recorder
}

// RunInTxn mocks base method.
func (m *MockTransactionManager) RunInTxn(ctx context.Context, fn txn.InTxn) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunInTxn", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunInTxn indicates an expected call of RunInTxn.
func (mr *MockTransactionManagerMockRecorder) RunInTxn(ctx, fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunInTxn", reflect.TypeOf((*MockTransactionManager)(nil).RunInTxn), ctx, fn)
}
